using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CS.SlotMachine.UI;

[GenerateTypedNameReferences]
public sealed partial class SlotMachineMenu : FancyWindow
{
    public Action<int>? PlayRequest;

    private bool _enabled;
    private bool _playing;
    private int _balance;
    private int _selectedAmount = 500;

    public SlotMachineMenu()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("slot-machine-menu-title");

        Bet500Button.OnPressed += _ => SelectAmount(500);
        Bet1000Button.OnPressed += _ => SelectAmount(1000);
        Bet5000Button.OnPressed += _ => SelectAmount(5000);
        Bet10000Button.OnPressed += _ => SelectAmount(10000);
        PlayButton.OnPressed += OnPlayPressed;

        SelectAmount(_selectedAmount);
    }

    public void SetBalance(int amount)
    {
        _balance = amount;
        BalanceLabel.Text = BankSystemExtensions.ToCreditString(amount);
        UpdatePlayButton();
    }

    public void SetJackpot(int amount)
    {
        JackpotLabel.Text = BankSystemExtensions.ToCreditString(amount);
    }

    public void SetEnabled(bool enabled)
    {
        _enabled = enabled;
        UpdatePlayButton();
    }

    public void SetPlaying(bool playing)
    {
        _playing = playing;
        UpdatePlayButton();
    }

    public void SetOutcome(string text)
    {
        OutcomeLabel.Text = text;
    }

    private void SelectAmount(int amount)
    {
        _selectedAmount = amount;
        SelectedLabel.Text = BankSystemExtensions.ToCreditString(amount);
        UpdatePlayButton();
    }

    private void OnPlayPressed(BaseButton.ButtonEventArgs obj)
    {
        if (PlayButton.Disabled)
            return;

        PlayRequest?.Invoke(_selectedAmount);
    }

    private void UpdatePlayButton()
    {
        PlayButton.Disabled = !_enabled || _playing || _balance < _selectedAmount;
    }
}